
package myloginsystem_Naraja;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form LoginUI_Naraja_ICT1
     */
    public Home() {
        initComponents();
        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Clive = new javax.swing.JLabel();
        PinkPantherSit = new javax.swing.JLabel();
        ThinkBauble = new javax.swing.JLabel();
        PinkPantherHead = new javax.swing.JLabel();
        PinkStand = new javax.swing.JLabel();
        Welcome = new javax.swing.JLabel();
        JBtnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        Clive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myloginsystem_Naraja/clive2.jpg"))); // NOI18N
        jPanel1.add(Clive);
        Clive.setBounds(80, 190, 160, 120);

        PinkPantherSit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myloginsystem_Naraja/Pink panther 2.png"))); // NOI18N
        jPanel1.add(PinkPantherSit);
        PinkPantherSit.setBounds(-110, 350, 360, 270);

        ThinkBauble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myloginsystem_Naraja/think3.png"))); // NOI18N
        jPanel1.add(ThinkBauble);
        ThinkBauble.setBounds(0, 140, 370, 310);

        PinkPantherHead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myloginsystem_Naraja/pink panther4.png"))); // NOI18N
        PinkPantherHead.setText("jLabel7");
        jPanel1.add(PinkPantherHead);
        PinkPantherHead.setBounds(440, 90, 130, 100);

        PinkStand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myloginsystem_Naraja/Pink stand.png"))); // NOI18N
        jPanel1.add(PinkStand);
        PinkStand.setBounds(790, 60, 350, 570);

        Welcome.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Welcome.setText("Welcome to my page!");
        jPanel1.add(Welcome);
        Welcome.setBounds(330, 200, 350, 40);

        JBtnLogout.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JBtnLogout.setText("Logout");
        JBtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnLogout);
        JBtnLogout.setBounds(440, 370, 130, 40);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnLogoutActionPerformed
        // TODO add your handling code here:
        new LoginUI_Naraja_ICT1().setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_JBtnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clive;
    private javax.swing.JButton JBtnLogout;
    private javax.swing.JLabel PinkPantherHead;
    private javax.swing.JLabel PinkPantherSit;
    private javax.swing.JLabel PinkStand;
    private javax.swing.JLabel ThinkBauble;
    private javax.swing.JLabel Welcome;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
