
package myloginsystem_Naraja;



public class LoginUI_Naraja_ICT1 extends javax.swing.JFrame {

    /**
     * Creates new form LoginUI_Naraja_ICT1
     */
    public LoginUI_Naraja_ICT1() {
        initComponents();
        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Clive = new javax.swing.JLabel();
        PinkPantherSit = new javax.swing.JLabel();
        ThinkBauble = new javax.swing.JLabel();
        LoginSystem = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        PinkPantherHead = new javax.swing.JLabel();
        UserField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        PinkStand = new javax.swing.JLabel();
        JBtnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        Clive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myloginsystem_Naraja/clive2.jpg"))); // NOI18N
        jPanel1.add(Clive);
        Clive.setBounds(80, 190, 160, 120);

        PinkPantherSit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myloginsystem_Naraja/Pink panther 2.png"))); // NOI18N
        jPanel1.add(PinkPantherSit);
        PinkPantherSit.setBounds(-110, 350, 360, 270);

        ThinkBauble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myloginsystem_Naraja/think3.png"))); // NOI18N
        jPanel1.add(ThinkBauble);
        ThinkBauble.setBounds(0, 140, 370, 310);

        LoginSystem.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LoginSystem.setText("Login System");
        jPanel1.add(LoginSystem);
        LoginSystem.setBounds(140, 30, 250, 50);

        Username.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Username.setText("User:");
        jPanel1.add(Username);
        Username.setBounds(340, 230, 60, 70);

        Password.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Password.setText("Password:");
        jPanel1.add(Password);
        Password.setBounds(290, 320, 110, 40);

        PinkPantherHead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myloginsystem_Naraja/pink panther4.png"))); // NOI18N
        PinkPantherHead.setText("jLabel7");
        jPanel1.add(PinkPantherHead);
        PinkPantherHead.setBounds(10, 10, 130, 100);

        UserField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        UserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserFieldActionPerformed(evt);
            }
        });
        jPanel1.add(UserField);
        UserField.setBounds(400, 240, 340, 50);

        PasswordField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PasswordField);
        PasswordField.setBounds(400, 320, 340, 50);

        PinkStand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myloginsystem_Naraja/Pink stand.png"))); // NOI18N
        jPanel1.add(PinkStand);
        PinkStand.setBounds(790, 60, 350, 570);

        JBtnLogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JBtnLogin.setText("Login");
        JBtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnLogin);
        JBtnLogin.setBounds(603, 390, 130, 40);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void JBtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnLoginActionPerformed
        // TODO add your handling code here:
        String user =UserField.getText();
        String pass =PasswordField.getText();
        
        if(user.equals("admin") && pass.equals("1234")) {
            new Home().setVisible(true);
            this.setVisible(false); //hide login frame
        }
    }//GEN-LAST:event_JBtnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI_Naraja_ICT1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI_Naraja_ICT1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI_Naraja_ICT1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI_Naraja_ICT1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI_Naraja_ICT1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clive;
    private javax.swing.JButton JBtnLogin;
    private javax.swing.JLabel LoginSystem;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PinkPantherHead;
    private javax.swing.JLabel PinkPantherSit;
    private javax.swing.JLabel PinkStand;
    private javax.swing.JLabel ThinkBauble;
    private javax.swing.JTextField UserField;
    private javax.swing.JLabel Username;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
