/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Naraja.numberaddition;

import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author user
 */
public class Naraja_NumberAdditionUI extends javax.swing.JFrame {

    /**
     * Creates new form Naraja_NumberAdditionUI
     */
    public Naraja_NumberAdditionUI() {
        initComponents();
        
        //Makes ResultField uneditable
        ResultField.setEditable(false);
        
    // Restrict FirstNumberField to only allow numbers
    FirstNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            char inputChar = evt.getKeyChar();
            if (!Character.isDigit(inputChar) && inputChar != '\b') { // Allows only numbers and delete(backspace) inputs
                evt.consume(); // Ignores characters that aren't numbers
            } } } );

    // Similar to FirstNumberField but for SecondNumberField
    SecondNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            char inputChar = evt.getKeyChar();
            if (!Character.isDigit(inputChar) && inputChar != '\b') { // Allows only numbers and delete(backspace) inputs
                evt.consume(); // Ignores characters that aren't numbers
            } } } );
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NumberAddition = new javax.swing.JPanel();
        FirstNumber = new javax.swing.JLabel();
        SecondNumber = new javax.swing.JLabel();
        Result = new javax.swing.JLabel();
        FirstNumberField = new javax.swing.JTextField();
        ResultField = new javax.swing.JTextField();
        SecondNumberField = new javax.swing.JTextField();
        JbtnClear = new javax.swing.JButton();
        JbtnAdd = new javax.swing.JButton();
        JbtnExit = new javax.swing.JButton();
        JbtnSubtract = new javax.swing.JButton();
        JbtnMultiply = new javax.swing.JButton();
        JbtnDivide = new javax.swing.JButton();
        Background = new javax.swing.JLabel();
        Background2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NumberAddition.setBackground(new java.awt.Color(255, 153, 255));
        NumberAddition.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Number Addition", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        NumberAddition.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FirstNumber.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        FirstNumber.setText("First Number:");
        NumberAddition.add(FirstNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 50));

        SecondNumber.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        SecondNumber.setText("Second Number:");
        NumberAddition.add(SecondNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 50));

        Result.setBackground(new java.awt.Color(255, 153, 153));
        Result.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Result.setText("Result:");
        NumberAddition.add(Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, 50));

        FirstNumberField.setBackground(new java.awt.Color(253, 215, 255));
        FirstNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNumberFieldActionPerformed(evt);
            }
        });
        FirstNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FirstNumberFieldKeyTyped(evt);
            }
        });
        NumberAddition.add(FirstNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 320, 50));

        ResultField.setEditable(false);
        ResultField.setBackground(new java.awt.Color(253, 215, 255));
        ResultField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultFieldActionPerformed(evt);
            }
        });
        ResultField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ResultFieldKeyTyped(evt);
            }
        });
        NumberAddition.add(ResultField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 320, 50));

        SecondNumberField.setBackground(new java.awt.Color(253, 215, 255));
        SecondNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondNumberFieldActionPerformed(evt);
            }
        });
        NumberAddition.add(SecondNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 320, 50));

        JbtnClear.setBackground(new java.awt.Color(255, 153, 255));
        JbtnClear.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JbtnClear.setText("Clear");
        JbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnClearActionPerformed(evt);
            }
        });
        NumberAddition.add(JbtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 150, 50));

        JbtnAdd.setBackground(new java.awt.Color(255, 153, 255));
        JbtnAdd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JbtnAdd.setText("Add");
        JbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnAddActionPerformed(evt);
            }
        });
        NumberAddition.add(JbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 130, 50));

        JbtnExit.setBackground(new java.awt.Color(255, 153, 255));
        JbtnExit.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JbtnExit.setText("Exit");
        JbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnExitActionPerformed(evt);
            }
        });
        NumberAddition.add(JbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 150, 50));

        JbtnSubtract.setBackground(new java.awt.Color(255, 153, 255));
        JbtnSubtract.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JbtnSubtract.setText("Subtract");
        JbtnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnSubtractActionPerformed(evt);
            }
        });
        NumberAddition.add(JbtnSubtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 130, 50));

        JbtnMultiply.setBackground(new java.awt.Color(255, 153, 255));
        JbtnMultiply.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JbtnMultiply.setText("Multiply");
        JbtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnMultiplyActionPerformed(evt);
            }
        });
        NumberAddition.add(JbtnMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 130, 50));

        JbtnDivide.setBackground(new java.awt.Color(255, 153, 255));
        JbtnDivide.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JbtnDivide.setText("Divide");
        JbtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDivideActionPerformed(evt);
            }
        });
        NumberAddition.add(JbtnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 130, 50));

        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Naraja/numberaddition/Pink Panther.png"))); // NOI18N
        NumberAddition.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 320, 430));

        Background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Naraja/numberaddition/Pink panther 2.png"))); // NOI18N
        NumberAddition.add(Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 192, 370, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NumberAddition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(NumberAddition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNumberFieldActionPerformed

    private void SecondNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecondNumberFieldActionPerformed

    private void ResultFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultFieldActionPerformed

    private void JbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnExitActionPerformed
    JFrame frame = new JFrame("Exit"); // Declare 'frame' here
    if (JOptionPane.showConfirmDialog(
            frame, 
            "Confirm if you want to exit", 
            "Number Calculator", 
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) { // Use YES_OPTION here
        System.exit(0); // Exit the application
    }
    }//GEN-LAST:event_JbtnExitActionPerformed

    private void JbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnAddActionPerformed
        // First we define float variables.
        float num1, num2, result;
        // We have to parse the text to a type float.
        num1 = Float.parseFloat(FirstNumberField.getText());
        num2 = Float.parseFloat(SecondNumberField.getText());
        // Now we can perform the addition.
        result = num1+num2;
        ResultField.setText(String.valueOf(result));
    }//GEN-LAST:event_JbtnAddActionPerformed

    private void JbtnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnMultiplyActionPerformed
        // TODO add your handling code here:
        float num1, num2, result;
        num1 = Float.parseFloat(FirstNumberField.getText());
        num2 = Float.parseFloat(SecondNumberField.getText());
         result = num1*num2;
         ResultField.setText(String.valueOf(result));
    }//GEN-LAST:event_JbtnMultiplyActionPerformed

    private void JbtnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnSubtractActionPerformed
        // TODO add your handling code here:
         float num1, num2, result;
        // We have to parse the text to a type float.
        num1 = Float.parseFloat(FirstNumberField.getText());
        num2 = Float.parseFloat (SecondNumberField.getText());
        // Now we can perform the subtraction.
        result = num1 - num2;
        // We will now pass the value of result to ResultField
        // We are also gonna change the value of result from float to a string.
        ResultField.setText(String.valueOf(result));
    }//GEN-LAST:event_JbtnSubtractActionPerformed

    private void JbtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDivideActionPerformed
        // TODO add your handling code here:
                float num1, num2, result;
        num1 = Float.parseFloat(FirstNumberField.getText());
        num2 = Float.parseFloat(SecondNumberField.getText());
         result = num1/num2;
         ResultField.setText(String.valueOf(result));
    }//GEN-LAST:event_JbtnDivideActionPerformed

    private void FirstNumberFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstNumberFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNumberFieldKeyTyped

    private void JbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnClearActionPerformed
        // Set clear textfields
            FirstNumberField.setText("");
                SecondNumberField.setText("");
                    ResultField.setText("");
    }//GEN-LAST:event_JbtnClearActionPerformed

    private void ResultFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ResultFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Naraja_NumberAdditionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Naraja_NumberAdditionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Naraja_NumberAdditionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Naraja_NumberAdditionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Naraja_NumberAdditionUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Background2;
    private javax.swing.JLabel FirstNumber;
    private javax.swing.JTextField FirstNumberField;
    private javax.swing.JButton JbtnAdd;
    private javax.swing.JButton JbtnClear;
    private javax.swing.JButton JbtnDivide;
    private javax.swing.JButton JbtnExit;
    private javax.swing.JButton JbtnMultiply;
    private javax.swing.JButton JbtnSubtract;
    private javax.swing.JPanel NumberAddition;
    private javax.swing.JLabel Result;
    private javax.swing.JTextField ResultField;
    private javax.swing.JLabel SecondNumber;
    private javax.swing.JTextField SecondNumberField;
    // End of variables declaration//GEN-END:variables
}
